language: php

git:
  quiet: true
  depth: 3

matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
    env: PHPUNIT_BIN=~/bin/phpunit-7.5.7 # PHPUnit 8 by default
  - php: 7.3
    env: PHPUNIT_BIN=~/bin/phpunit-7.5.7 # PHPUnit 8 by default

services:
 - mysql

before_script:
 - ./tests/travis_setup_mysql.sh racktables_unittest racktables travistest
 - mkdir -p ~/bin
 - curl -sSfL -o ~/bin/phpunit-7.5.7 https://phar.phpunit.de/phpunit-7.5.7.phar
 - chmod a+x ~/bin/phpunit-7.5.7

script:
 - ./tests/express_pre.sh
 - if [ "$SKIP_PHPUNIT" = yes ]; then echo '(skipped PHPUnit tests on request)'; else ./tests/express_phpunit.sh; fi
 - ./tests/express_post.sh
 - mysql -u racktables -ptravistest racktables_unittest < scripts/init-sample-racks.sql
 - DESTDIR=/tmp make install
